export const USER_CHATS_REQUEST = 'USER_CHATS_REQUEST'
export const USER_CHATS_SUCCESS = 'USER_CHATS_SUCCESS'
export const USER_CHATS_FAIL = 'USER_CHATS_FAIL'

export const NEW_CHAT_REQUEST = 'NEW_CHAT_REQUEST'
export const NEW_CHAT_SUCCESS = 'NEW_CHAT_SUCCESS'
export const NEW_CHAT_FAIL = 'NEW_CHAT_FAIL'